version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./svc.json
    volumes:
      - .:/go/src/app